### ISSUE TITLE
How can i get errors and mistakes

### ISSUE THREAD

**Issue by vitorregisrr** [jchamill/jquery-quiz#1]
How can I get the number of errors and success with JAVA? is there a way? What is the name of the variable that holds these datas?
My back-end need to get this data and send it to the database using JAVA, I need to save the results for later analysis.
Very good, easy and functional your framework, congratulations and thank you!

**Comment by jchamill** [comment]
Yes, you can do this using the callbacks. Use the answerCallback to keep track of the number of correct/incorrect responses. Note that the answerCallback accepts two parameters, the second parameter is a boolean that represents if the user answered the question correctly. Then you can use the finishCallback to then send the data to a backend system. Of course, you will have to write your own code in the callbacks to send the data to a backend system. There is a callback example in the demos folder.
