### ISSUE TITLE
How to randomize this quiz? 

### ISSUE THREAD

**Issue by YashiChaturvedi** [jchamill/jquery-quiz#11]
I want to randomize the quiz questions and questions should also not repeat itself

**Comment by jchamill** [comment]
I've added two new callbacks, setupCallback and resetCallback, which will allow you to shuffle the questions before the quiz starts, after the quiz is restarted, and after the home button is clicked. I've added shuffle functionality to the callbacks.html demo, which can be found in the demo directory.
