### ISSUE TITLE
Problem with text options

### ISSUE THREAD

**Issue by jeremy174433** [jchamill/jquery-quiz#12]
When I try to use the variables to change the text like "resultsFormat" or "finishButtonText", this does'nt work, it will display the default text but if I try with the var "counterFormat" it work. (other variable like "counter" works well).
I use strings everywhere, the plugin is correctly installed and jQuery also.

**Comment by jchamill** [comment]
Have a look at localization.html in the demo directory. It changes the finishButtonText and the resultsFormat text. Make sure your code is initializing those values the way it is in the demo. If this is still an issue, please share the code used to cause this issue.
