### ISSUE TITLE
Images to questions

### ISSUE THREAD

**Issue by gevrip** [jchamill/jquery-quiz#14]
Hi
Love the script but I'm still struggling to add images to some questions from a http link but still it doesn't display or it displays at all questions, if anyone know how I can make help will be appreciated thanks

**Comment by jchamill** [comment]
You can add html to the question or answer in the javascript questions configuration. I've updated the demos to illustrate this (see basic.html in the demos directory).

For example, you can do this directly in the question config:
`'q': 'What is this image? <img src="https://picsum.photos/100/100">'`

Or you can do it for the answers:
`'options': ['<img src="https://picsum.photos/100/100">', '<img src="https://picsum.photos/100/100">']`

Hope this helps!

**Comment by gevrip** [comment]
It works perfect thank you sir, really appreciate it
