### ISSUE TITLE
Adding correct answer on event

### ISSUE THREAD

**Issue by erikickes** [jchamill/jquery-quiz#2]
Unless i'm missing something there does not seem to be a way to highlight the correct answer when they pick an incorrect one. We would like to be able to highlight the red chosen option but also indicate the correct option in green. Perhaps this can be done in callbacks but we're not finding a way to index it.

**Comment by jchamill** [comment]
I've updated the answer callback to send the current question object as the 3rd parameter. Note the second parameter has been updated as well. It was a boolean that was true if the answer was correct, false if incorrect. It is now the selected question index. You can see the demo/callbacks.html example to see how to highlight the correct index if the question was incorrect.
