### ISSUE TITLE
How to use multiple query sets for different selectors in the quiz.js plugin?

### ISSUE THREAD

**Issue by seAfnan** [jchamill/jquery-quiz#5]
I am using a Bootstrap Modal for queries. I want to load different query sets based upon the selected options in dropdown. But the problem is, $('#quiz').quiz({}) loads on page load and pass the first query set and don't replace with the other query set when we change option in dropdown. I don't know how to fix this ...

**Comment by jchamill** [comment]
This is a very late response and so it is probably not helpful at this point. But for what it's worth, the current version of the quiz plugin does not support multiple quizzes on a single page. This is something I plan to add in a future release.
