### ISSUE TITLE
Awesome script

### ISSUE THREAD

**Issue by inglesuniversal** [jchamill/jquery-quiz#7]
How can I hide the restart button at the end of the quiz and replace it with a form to get the users personal info (email, name, etc)

Regards

Hugo

**Comment by 381e35** [comment]
> How can I hide the restart button at the end of the quiz and replace it with a form to get the users personal info (email, name, etc)

Almost a year later, but for anyone that is still using this script you can do this quite easily.

Create a div in the `#quiz-container` that has the id `#quiz-results-screen`. You can also change the id of the div required by changing the default option when creating your quiz object with `resultsScreen: "#<your_div>"`.

To create a custom action that you can still control within the script you could just fork this project and customize it to fit your needs. 

A few things you will likely want to add are: 
 * HTML safe responses.
 * Custom styling to fit the rest of the website.
 * Changed the question p tag to an h1 tag
 * Automatic response filtering with correct/incorrect
 * Link building for the response section
 * Automatic scrolling to the top of the page
 * Share button to promote the sharing of the quiz

The script isn't that big and is set up pretty much ready for you to customize to fit your needs.

**Comment by jchamill** [comment]
This is probably too late to matter but I've added a new custom-results-screen.html to the demo directory. It just illustrates the point that @ChanceHerriage was explaining.

**Comment by inglesuniversal** [comment]
Never too late for improvements!!!
